version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=production
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-change-me}
      - ADMIN_SECRET=${ADMIN_SECRET:-20252025}
      - DATABASE_URL=sqlite:///./data/time_tracker.db
      - HOST=0.0.0.0
      - PORT=8001
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./app/static:/app/static:ro
    depends_on:
      - web
    restart: unless-stopped

  # Опционально: PostgreSQL для продакшена
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: time_tracker
  #     POSTGRES_USER: ${DB_USER:-timetracker}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
