#!/bin/bash

echo "🎨 Настройка CSS стилей для work.maxmobiles.ru..."
echo "================================================"

echo "🔧 Исправления, которые были внесены:"
echo "   ✅ Исправлен путь в nginx.conf: /app/app/static/ → /app/static/"
echo "   ✅ Исправлен путь в docker-compose.yml: /app/app/static → /app/static"
echo "   ✅ Обновлен домен: yourdomain.com → work.maxmobiles.ru"

echo ""
echo "📁 Структура файлов:"
echo "   • CSS файл: ./app/static/css/styles.css"
echo "   • URL: http://work.maxmobiles.ru/static/css/styles.css"
echo "   • Nginx location: /static/ → /app/static/"

echo ""
echo "🚀 Команды для применения на сервере:"
echo ""
echo "# Остановить контейнеры"
echo "docker-compose down"
echo ""
echo "# Пересобрать образы"
echo "docker-compose build --no-cache"
echo ""
echo "# Запустить контейнеры"
echo "docker-compose up -d"
echo ""
echo "# Проверить статус"
echo "docker-compose ps"
echo ""
echo "# Проверить логи nginx"
echo "docker-compose logs nginx"

echo ""
echo "🔍 Проверка CSS доступности:"
echo "curl -I http://work.maxmobiles.ru/static/css/styles.css"
echo ""
echo "Должен вернуть: HTTP/1.1 200 OK и Content-Type: text/css"

echo ""
echo "📋 Альтернативная конфигурация (HTTP без SSL):"
echo "   • Файл: nginx-http.conf"
echo "   • Docker-compose: docker-compose-http.yml"
echo "   • Для использования: docker-compose -f docker-compose-http.yml up -d"

echo ""
echo "✅ Готово! CSS стили теперь настроены для правильного пути."
echo "   После применения изменений CSS будет доступен по адресу:"
echo "   http://work.maxmobiles.ru/static/css/styles.css"
